### ISSUE TITLE
TypeError: Cannot read property 'hash' of undefined

### ISSUE THREAD

**Issue by pustovalov** [mzgoddard/hard-source-webpack-plugin#416]
### Expected Behavior

Successful compilation from the first time

### Actual Behavior

The first compilation failed, the second successful

#### Is an error being thrown?

debug:

```
function updateMd5CacheItem(value) {
  if (md5Cache[file]) {
    console.log('file', file)
    console.log('md5Cache[file]', md5Cache[file])
    console.log('value', value)
  }
  if (
    !md5Cache[file] ||
    (md5Cache[file] && md5Cache[file].hash !== value.hash)
  ) {
```

log:
```
file /app/assets/stylesheets/themes/shared/_flex.scss
md5Cache[file] { mtime: 1533291733713,
  hash: 'a57c36d6619fa2b99458d0f2d4045d74',
  isFile: true,
  isDirectory: false }
value { mtime: 1533291735643,
  hash: 'a57c36d6619fa2b99458d0f2d4045d74',
  isFile: true,
  isDirectory: false }
file /vendor/assets/stylesheets/_spaces.sass
md5Cache[file] { mtime: 1533291734298,
  hash: '24f5e6afc9adbd8007d9bb8aaf881ddb',
  isFile: true,
  isDirectory: false }
value { mtime: 1533291735643,
  hash: '24f5e6afc9adbd8007d9bb8aaf881ddb',
  isFile: true,
  isDirectory: false }
file /app/assets/stylesheets/application_v2/_config.sass
md5Cache[file] { mtime: 1533291733710,
  hash: '70d356e279b46ee8dc81ab0173772507',
  isFile: true,
  isDirectory: false }
value undefined
file /app/assets/stylesheets/themes/shared/_utils.sass
md5Cache[file] { mtime: 1533291733712,
  hash: 'b151941279dbf615b1cc28bfcded8f38',
  isFile: true,
  isDirectory: false }
value undefined
TypeError: Cannot read property 'hash' of undefined
    at updateMd5CacheItem (/node_modules/hard-source-webpack-plugin/lib/CacheMd5.js:373:66)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Steps to Reproduce

just run `webpack-dev-server`

### Operating System, Node, and NPM dependency versions

```
Mac OS 10.13.6
Node 10.7.0
webpack: 3.12.0
hard-source-webpack-plugin 0.12.0

"dependencies": {
  "@rails/webpacker": "3.5",
  "at.js": "^1.5.3",
  "autoprefixer": "^8.x",
  "babel-plugin-dynamic-import-webpack": "^1.0.2",
  "babel-plugin-styled-components": "^1.5.1",
  "babel-plugin-transform-decorators-legacy": "^1.3.4",
  "babel-plugin-transform-do-expressions": "^6.22.0",
  "babel-polyfill": "^6.26.0",
  "babel-preset-env": "^1.6.0",
  "babel-preset-react": "^6.24.1",
  "babel-preset-stage-2": "^6.24.1",
  "balloon-css": "^0.5.0",
  "caniuse-lite": "^1.0.30000697",
  "cjsx-loader": "^3.0.0",
  "classnames": "^2.2.5",
  "clipboard": "^2.0.1",
  "coffee-loader": "^0.9.0",
  "coffeescript": "^2.3.1",
  "compression-webpack-plugin": "^1.0.0",
  "create-react-class": "^15.6.3",
  "dropzone": "^5.3.0",
  "expose-loader": "^0.7.3",
  "filesize": "^3.6.1",
  "glob": "^7.1.2",
  "highcharts": "^6.0.4",
  "highlight.js": "9.12.0",
  "jquery": "^1.12.3",
  "jquery.caret": "^0.3.1",
  "js-yaml": "^3.9.1",
  "lodash": "^4.17.10",
  "mobx": "^4.3.1",
  "mobx-devtools-mst": "^0.9.18",
  "mobx-react": "^5.2.3",
  "mobx-react-form": "^1.32.2",
  "mobx-react-form-devtools": "^1.7.2",
  "mobx-state-tree": "^2.2.0",
  "moment-timezone": "^0.5.14",
  "node-sass": "^4.8.3",
  "path-complete-extname": "^0.1.0",
  "pluralize": "^7.0.0",
  "postcss-smart-import": "^0.7.5",
  "precss": "^2.0.0",
  "prop-types": "^15.6.0",
  "query-string": "^5.1.0",
  "rails-erb-loader": "^5.4.2",
  "react": "^16.2.0",
  "react-bootstrap": "0.31.5",
  "react-dom": "^16.2.0",
  "react-helmet": "^5.2.0",
  "react-loadable": "^5.3.1",
  "react-router-dom": "^4.3.1",
  "react-router-navigation-prompt": "^1.5.5",
  "react-scroll": "^1.7.9",
  "react-simple-colorpicker": "^1.x",
  "react-textarea-autosize": "^6.1.0",
  "resolve-url-loader": "^2.1.0",
  "sass-loader": "^7.0.3",
  "sortablejs": "^1.7.0",
  "stickyfilljs": "^2.0.3",
  "styled-components": "3.2.6",
  "stylelint": "^8.3.0",
  "stylelint-config-standard": "^18.0.0"
},
"devDependencies": {
  "babel-eslint": "^8.2.3",
  "babel-plugin-transform-es2015-modules-commonjs": "^6.26.2",
  "enzyme": "^3.3.0",
  "enzyme-adapter-react-16": "^1.1.1",
  "eslint": "^4.19.1",
  "eslint-config-standard": "^10.2.1",
  "eslint-config-standard-react": "^5.0.0",
  "eslint-plugin-babel": "^4.1.2",
  "eslint-plugin-import": "^2.7.0",
  "eslint-plugin-node": "^5.1.1",
  "eslint-plugin-promise": "^3.5.0",
  "eslint-plugin-react": "^7.3.0",
  "eslint-plugin-standard": "^3.0.1",
  "hard-source-webpack-plugin": "^0.12.0",
  "jest": "^23.2.0",
  "jest-enzyme": "^6.0.2",
  "jest-html": "^1.4.0",
  "jest-serializer-enzyme": "^1.0.0",
  "jest-serializer-html": "^5.0.0",
  "jest-styled-components": "^5.0.1",
  "mobx-devtools-mst": "^0.9.18",
  "prettier": "^1.7.4",
  "webpack-bundle-analyzer": "^2.10.0",
  "webpack-dev-server": "2.11.2"
},
```

plugin configuration:
```
const HardSourceWebpackPlugin = require('hard-source-webpack-plugin')
environment.plugins.prepend('HardSourceWebpackPlugin',
  new HardSourceWebpackPlugin()
)
```

**Comment by mzgoddard** [comment]
@pustovalov can you confirm that _config.sass or _utils.sass appear only once in the debug output. I'm wondering if they are somehow trying to update their hashes twice. I'm not sure how that could happen though.

**Comment by pustovalov** [comment]
@mzgoddard debug:
```
            function updateMd5CacheItem(value) {
              if (file.includes('_config.sass')) {
                console.log('file', file)
              }
```

output:
```
404s will fallback to /index.html
[hardsource:de83c073] Tracking node dependencies with: yarn.lock.
 69% building modules 1690/1696 modules 6 active .../bundles/customer-service-portal.scssfile /app/assets/stylesheets/application_v2/_config.sass
file /app/assets/stylesheets/application_v2/_config.sass
file /app/assets/stylesheets/application_v2/_config.sass
file /app/assets/stylesheets/application_v2/_config.sass
 94% asset optimizationfile /app/assets/stylesheets/application_v2/_config.sass
file /app/assets/stylesheets/application_v2/_config.sass
TypeError: Cannot read property 'hash' of undefined
    at updateMd5CacheItem (/node_modules/hard-source-webpack-plugin/lib/CacheMd5.js:376:66)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by niieani** [comment]
Same thing here: 

```
[hardsource:6f72a45a] Could not freeze ./app-entries/settings.js + 23 modules: Cannot read property 'hash' of undefined
```

**Comment by blackbird91** [comment]
Same problem here. This issue seems to appear after the latest webpack update (4.16.4 -> 4.16.5)

**Comment by ndevvy** [comment]
I am getting this error with webpack 4.16.4.

**Comment by nuintun** [comment]
Same problem

![_20180808095205](https://user-images.githubusercontent.com/1730277/43811772-db39f296-9af0-11e8-87de-e7acae00c829.png)

**Comment by 7iomka** [comment]
any solutions? :(

**Comment by jamie-pi** [comment]
I'm having the same problem

**Comment by 10ndavis** [comment]
Ditto.

**Comment by codart1** [comment]
Same here 
```
[hardsource:748ccae8] Could not freeze ./node_modules/xtend/immutable.js: Cannot read property 'hash' of undefined
[hardsource:748ccae8] Could not freeze ./node_modules/zen-observable-ts/lib/index.js: Cannot read property 'hash' of undefined
[hardsource:748ccae8] Could not freeze ./node_modules/zen-observable-ts/lib/zenObservable.js: Cannot read property 'hash' of undefined
[hardsource:748ccae8] Could not freeze ./node_modules/zen-observable-ts/node_modulesWebpack: Starting ...
```

**Comment by Mathieuu** [comment]
Same problem

**Comment by chrismwendt** [comment]
Removing `node-sass-import-once` in one of my projects seems to fix it, but the CSS output is different and it broke the UI.

**Comment by 7iomka** [comment]
Latest version broke usage of `browsersync ` plugin (auto-inject css not works as expected, long time, and multiple reloads)
Version of hardsource which I now use (to somehow work) is ^0.6.4
I'm sad

**Comment by pustovalov** [comment]
possible solution: for this repository and merge this PR: https://github.com/mzgoddard/hard-source-webpack-plugin/pull/419

**Comment by evanstern** [comment]
The solution from @MrLesAubrey has worked for me so far. I guess if I see this error again I'll just do as he recommended (remove the contents of `node_modules/.cache/hard-source` directory).

**Comment by mojilla** [comment]
same problem after updating dep

**Comment by pustovalov** [comment]
you can try to use this in `package.json`: 

```
{
  "hard-source-webpack-plugin": "https://github.com/talkable/hard-source-webpack-plugin#build",
}
```

but it's better to use your own fork

**Comment by kevindurb** [comment]
Im also gettng this error too. It goes away for a bit when i delete my cache folder but then will come back seemingly randomly

**Comment by cchamberlain** [comment]
@pustovalov just forked yours and it worked first try. Haven't done enough testing to see if it will come back but I had a complete blocking issue after installing `webpack-watch-files-plugin` which I couldn't progress past prior to forking so thanks!

**Comment by antonellil** [comment]
I am seeing this error as well `Could not freeze  /path/to/file: Cannot read property 'hash' of undefined`, noticed that it seems to be happening only for files which contain async-loaded imports, or are dependencies of async-loaded imports

**Comment by secabhi** [comment]
Even this error is occurring the build is working fine for me. At least its not breaking anything . If its breaking anything please let me know

**Comment by jamie-pi** [comment]
Not sure why this works, or whether it will for anyone else, but our package-lock.json in our repo was unversioned for some reason and mine seemed to be causing me more problems than my colleague's. Once he versioned his package-lock.json I replaced mine and I don't seem to be having as many problems now. Make of it what you will.

**Comment by xwchris** [comment]
same problem~

**Comment by kadamwhite** [comment]
We've been running into this too, I just had to remove this plugin from one of our projects to unblock a client team. I agree that merging #419 seems like a good path forward; @mzgoddard is there anything I can do to assist or test?

**Comment by MateusDantas** [comment]
Same problem here, removing the cache solved the issue. How far out are we from releasing the fix? We are running a big team of devs and we are starting to get this issue more frequently than we want to.

**Comment by pustovalov** [comment]
@MateusDantas have you tried this way https://github.com/mzgoddard/hard-source-webpack-plugin/issues/416#issuecomment-417699776?

**Comment by FishOrBear** [comment]
@mzgoddard  Can you solve this problem first?

**Comment by zhangyuwinnie** [comment]
Adding the '@babel/plugin-proposal-class-properties' plugin fixed this issue for me.

**Comment by zhangyuwinnie** [comment]
It seems adding the plugin '@babel/plugin-proposal-class-properties' fixed the issue for me.

**Comment by ljones87** [comment]
I was able to solve this problem by listing babel-polyfill as the first entry point in my webpack.config.js

```
entry: [
  'babel-polyfill',
  './src/webpack-public-path',
  ...
]
```

**Comment by wsjscss** [comment]
Same problem... Deleting `node_mobules/.cache/hard-source` folder not helps

**Comment by jwmann** [comment]
Yea I'm also getting this issue. Only seems to be happening to me `.less` files.

I've actually had this issue before and would just clear the cache as suggested above, but now it no longer seems to do anything.

**Comment by adamthompson922** [comment]
Seeing the same issue with `webpack` version `4.28.4`.

Unfortunately #419 does not fix the issue in my case.

**Comment by intelliapps-io** [comment]
I have the same issue. Perhaps it is an issue assessing static node_module files?

[Screenshot](https://i.imgur.com/6XsXz6E.png)

**Comment by adamthompson922** [comment]
@intelliapps-io I tried upgrading to `4.29.0` but still am seeing the same error.

**Comment by adamthompson922** [comment]
In my case it seems to be fail with `mini-css-extract-plugin` but not `style-loader`.

**Comment by mtmacdonald** [comment]
I'm also getting this issue.

<img width="863" alt="screenshot 2019-01-23 at 09 41 57" src="https://user-images.githubusercontent.com/2428859/51593733-2c433900-1ef3-11e9-99c8-1a6e6a007f62.png">

**Comment by FishOrBear** [comment]
![image](https://user-images.githubusercontent.com/19372111/51729675-a91b1200-20af-11e9-9ed6-922532116c9e.png)


This modification, you can skip the error, but the compilation speed is still slow, you can only delete the cache folder.

**Comment by slavoroi** [comment]
The same happens to me with 4.29.0 and hard source 0.13.1.
apollo-link, ui router and a few more files get a warning.

**Comment by callowaylc** [comment]
@mzgoddard any updates here? Also, and I don't understand how this isn't obvious to everyone, but deleting the cache and hoping for the best, is **NOT** a fix.

**Comment by ansballard** [comment]
My workaround for now is just to add a `prewatch` task that clears my `node_modules/.cache` directory, since I don't care as much if my production build or first iteration of `watch`ing is super fast, I just want to iterate quickly.

Here's the relevant section of my `package.json` using the `rimraf` package to clear the entire cache (may clear other package caches).

```json
{
  "scripts": {
    "prewatch": "rimraf ./node_modules/.cache"
    "watch": "webpack --watch"
  }
}

So far I haven't had issues, besides the fact that my initial `npm run watch` much slower, and that my config is now slightly more cluttered. YMMV.

**Comment by adamthompson922** [comment]
@ansballard that works well for your use case, but many of us are using this plugin for the opposite use case. For example, we are using it alongside `webpack-dev-middleware` to speed up the first webpack build rather than re-building the entire webpack bundle on every server restart.

**Comment by webdeb** [comment]
@mzgoddard I started using your plugin and got that error, too. It seems, that there might me some race conditions issues with all the references.

I assuming, that this happens only after the initial buildobj was created, so I tried to just ignore that error:

```
function updateMd5CacheItem(value) {
   if (!value) return;

  ...
``

And it worked. Got my cache warm, and after restarting everything was fine. Just wanted to point out, that maybe we can just silently ignore this error (I guess its a race-condition thing .

**Comment by Magin-CC** [comment]
https://www.npmjs.com/package/hard-source-webpack-plugin#excludemoduleplugin
it  work  for me.

**Comment by soederpop** [comment]
This seems to happen because the frozen module doesn't have a `build` property when you try to compare the hash.  It happens for me in any of the assets imported by my .less files.  And it seems to be a race condition.  Oh boy. 😰

**Comment by wiadev** [comment]
I've upgraded to hard-source-webpack@0.13.1 and it's resolved now.

**Comment by mbrochh** [comment]
Not for me. I'm on 0.13.1 as well and am getting these errors still.

When I delete the `.cache/hard-source` folder, the issue goes away for a while, but as I continue working it eventually comes back. Haven't figured out any pattern, yet :(

It seems, though, as soon as I edit something in my `App.tsx` file, the errors appear. I'm using this with Razzle and Typescript, if that matters.

**Comment by Magin-CC** [comment]
> Not for me. I'm on 0.13.1 as well and am getting these errors still.
> 
> When I delete the `.cache/hard-source` folder, the issue goes away for a while, but as I continue working it eventually comes back. Haven't figured out any pattern, yet :(
> 
> It seems, though, as soon as I edit something in my `App.tsx` file, the errors appear. I'm using this with Razzle and Typescript, if that matters.

do you use less ?

**Comment by mbrochh** [comment]
@Magin-CC nope, I do not use less.

**Comment by mbrochh** [comment]
I'm not 100% sure yet if this is the solution, but it turns out, I had node version 10.8.0 installed. I just upgraded to 12.3.1 and it seems like this warning no longer show up.

**Comment by arpowers** [comment]
hey guys, here's your solution: 

```javascript
new HardSourceWebpackPlugin({
            info: {
              level: "error"
            }
          }),
          new HardSourceWebpackPlugin.ExcludeModulePlugin([
            {
              test: /less-loader/
            }
          ])
```

**Comment by yucopowo** [comment]
it work for me

```js
new HardSourceWebpackPlugin.ExcludeModulePlugin([
            {
                // HardSource works with mini-css-extract-plugin but due to how
                // mini-css emits assets, assets are not emitted on repeated builds with
                // mini-css and hard-source together. Ignoring the mini-css loader
                // modules, but not the other css loader modules, excludes the modules
                // that mini-css needs rebuilt to output assets every time.
                test: /mini-css-extract-plugin[\\/]dist[\\/]loader/,
            },
```

**Comment by Stuk** [comment]
While I don't know the root cause of this error, I was able to fix it locally by removing the hard-source cache:

```
 rm -r node_modules/.cache/hard-source/
```

**Comment by leedommax** [comment]
> I am seeing this error as well `Could not freeze /path/to/file: Cannot read property 'hash' of undefined`, noticed that it seems to be happening only for files which contain async-loaded imports, or are dependencies of async-loaded imports
sure, I agree

**Comment by huoyuxin** [comment]
it seems that it's caused by bad cache, so i create a pr to clean cache
https://github.com/mzgoddard/hard-source-webpack-plugin/pull/519

**Comment by Choiyos** [comment]
it work for me.

http://www.arbaouimehdi.com/how-to-solve-the-cannot-read-property-hash-of-undefined/

**Comment by mean-cj** [comment]
package.json
```
  "scripts": {
    "clean": "rimraf ./node_modules/.cache/hard-source"
  },

```
yean clean


it work for me.

**Comment by AndrewBogdanovTSS** [comment]
> Not for me. I'm on 0.13.1 as well and am getting these errors still.
Same here, only manually deleting the cache folder helps

**Comment by smancang** [comment]
use "hard-source-webpack-plugin-fixed-hashbug" instead. I've already have a try, it works.

**Comment by Stuk** [comment]
@spion If [the change](https://github.com/spion/hard-source-webpack-plugin/commit/6a937ee33cd9c973a8fa82cd03da432fe922340c) that is published in `hard-source-webpack-plugin-fixed-hashbug` does fix this issue, would you mind creating a PR into this repo?

**Comment by spion** [comment]
Its been in a PR #497 since April 2019.

**Comment by pustovalov** [comment]
incremental builds:
```
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
[hardsource:e9805ddf] Using 14146 MB of disk space.
[hardsource:e9805ddf] Last compilation did not finish saving. Building new cache.
ℹ ｢wdm｣: Hash: c543a988069b8354c110
Version: webpack 4.42.1
Time: 5834ms
```

```
$ watch -i 60 du -sh node_modules/.cache/hard-source
403M	node_modules/.cache/hard-source
403M	node_modules/.cache/hard-source
436M	node_modules/.cache/hard-source
581M	node_modules/.cache/hard-source
597M	node_modules/.cache/hard-source
662M	node_modules/.cache/hard-source
678M	node_modules/.cache/hard-source
759M	node_modules/.cache/hard-source
791M	node_modules/.cache/hard-source
807M	node_modules/.cache/hard-source
840M	node_modules/.cache/hard-source
905M	node_modules/.cache/hard-source
953M	node_modules/.cache/hard-source
986M	node_modules/.cache/hard-source
1.0G	node_modules/.cache/hard-source
1.1G	node_modules/.cache/hard-source
1.2G	node_modules/.cache/hard-source
1.4G	node_modules/.cache/hard-source
1.5G	node_modules/.cache/hard-source
1.6G	node_modules/.cache/hard-source
1.7G	node_modules/.cache/hard-source
1.8G	node_modules/.cache/hard-source
1.9G	node_modules/.cache/hard-source
2.0G	node_modules/.cache/hard-source
2.1G	node_modules/.cache/hard-source

ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
[hardsource:e9805ddf] Using 2094 MB of disk space.
[hardsource:e9805ddf] Last compilation did not finish saving. Building new cache.
ℹ ｢wdm｣: Hash: ab284ecbe1b9831bc475
Version: webpack 4.42.1
Time: 2167ms
```

after removing `hard-source-webpack-plugin`:
```
ℹ ｢wdm｣: Compiling...
ℹ ｢wdm｣: Hash: 04025fd155acf6ed4fb1
Version: webpack 4.42.1
Time: 306ms
```

at the moment this plugin does more harm than good

**Comment by CyberDex** [comment]
Спасибо, пофиксил…   From: Pavel PustovalovSent: 16 апреля 2020 г. 22:21To: mzgoddard/hard-source-webpack-pluginCc: Dmytro Soldatov; ManualSubject: Re: [mzgoddard/hard-source-webpack-plugin] TypeError: Cannot read property 'hash' of undefined (#416) incremental builds:ℹ ｢wdm｣: Compiled successfully. ℹ ｢wdm｣: Compiling... [hardsource:e9805ddf] Using 14146 MB of disk space. [hardsource:e9805ddf] Last compilation did not finish saving. Building new cache. ℹ ｢wdm｣: Hash: c543a988069b8354c110 Version: webpack 4.42.1 Time: 5834ms $ watch -i 60 du -sh node_modules/.cache/hard-source 403M    node_modules/.cache/hard-source 403M    node_modules/.cache/hard-source 436M    node_modules/.cache/hard-source 581M    node_modules/.cache/hard-source 597M    node_modules/.cache/hard-source 662M    node_modules/.cache/hard-source 678M    node_modules/.cache/hard-source 759M    node_modules/.cache/hard-source 791M    node_modules/.cache/hard-source 807M    node_modules/.cache/hard-source 840M    node_modules/.cache/hard-source 905M    node_modules/.cache/hard-source 953M    node_modules/.cache/hard-source 986M    node_modules/.cache/hard-source 1.0G    node_modules/.cache/hard-source 1.1G    node_modules/.cache/hard-source 1.2G    node_modules/.cache/hard-source 1.4G    node_modules/.cache/hard-source 1.5G    node_modules/.cache/hard-source 1.6G    node_modules/.cache/hard-source 1.7G    node_modules/.cache/hard-source 1.8G    node_modules/.cache/hard-source 1.9G    node_modules/.cache/hard-source 2.0G    node_modules/.cache/hard-source 2.1G    node_modules/.cache/hard-source   ℹ ｢wdm｣: Compiled successfully. ℹ ｢wdm｣: Compiling... [hardsource:e9805ddf] Using 2094 MB of disk space. [hardsource:e9805ddf] Last compilation did not finish saving. Building new cache. ℹ ｢wdm｣: Hash: ab284ecbe1b9831bc475 Version: webpack 4.42.1 Time: 2167ms after removing hard-source-webpack-plugin:ℹ ｢wdm｣: Compiling... ℹ ｢wdm｣: Hash: 04025fd155acf6ed4fb1 Version: webpack 4.42.1 Time: 306ms at the moment this plugin does more harm than good—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by wanliyunyan** [comment]
"hard-source-webpack-plugin": "^0.13.1",
 "webpack": "^4.43.0",
"less-loader": "^5.0.0",-->  "^6.0.0" 

i upgrade less-loader form5 to 6 , same issue

**Comment by brainz80** [comment]
I keep getting
```
TypeError: Cannot read property 'hash' of undefined
    at updateMd5CacheItem (D:\Programming\work\aso-app\node_modules\hard-source-webpack-plugin-fixed-hashbug\lib\CacheMd5.js:368:66)
    at async Promise.all (index 0)
```
when trying to build my project. I've updated less-loader to 6.0.0.
Tested @spion PR and it didn't help.

**Comment by brainz80** [comment]
Found a work-around for my problem (https://github.com/mzgoddard/hard-source-webpack-plugin/issues/416#issuecomment-623428318). The problem seems to have been with `<style lang="less">@import "~floating-scroll/src/jquery.floatingscroll.less";</style>` in one of my project files. Luckily I had the chance to change it to `<style>@import "~floating-scroll/dist/jquery.floatingscroll.css";</style>`. And circumvent `less-loader`

**Comment by xc2f** [comment]
Same issue with less-loader@6.1.0

**Comment by davidwang1988** [comment]
for me, remove the two folders and fixed
node_modules/.cache/babel-loader
node_modules/.cache/cache-loader

**Comment by AndrewBogdanovTSS** [comment]
Guys, I really think that this plugin should no longer be used. It haven't been updated for 2 years and I strongly feel that it's developers just abandoned it. Maybe someone could prose an alternative to this one?

**Comment by salemhilal** [comment]
I believe Webpack 5 implements something like this plugin natively, right?

**Comment by kadamwhite** [comment]
w/r/t Webpack 4, and @AndrewBogdanovTSS's point, we want to find this a maintainer who is using it who has time. @mzgoddard hasn't indicated he has the time or interest any longer, and while I have the interest, I do not have the time. 

Per #525, if any of you have bandwidth to get some bugfixes merged, I would be happy to induct new maintainers. Right now I don't know which of the dozens of commits and comments on these issue chains actually represents the most up to date solution, and unfortunately I don't have time; but we _can_ get fixes merged, and if somebody wants to propose an alternative it would probably be better for the plugin's userbase if that activity happens here than if another fork gets created.

Thanks for all your thoughts, please reach out on the other issue if any of you are interested in contributing to this plugin :)

**Comment by s373r** [comment]
Just for the record, I got the error only after setting `'mode': 'development'` in my webpack config.

For `'mode': 'production'` no error at all -- hope it helps a bit

**Comment by PLQin** [comment]
> it work for me
> 
> ```js
> new HardSourceWebpackPlugin.ExcludeModulePlugin([
>             {
>                 // HardSource works with mini-css-extract-plugin but due to how
>                 // mini-css emits assets, assets are not emitted on repeated builds with
>                 // mini-css and hard-source together. Ignoring the mini-css loader
>                 // modules, but not the other css loader modules, excludes the modules
>                 // that mini-css needs rebuilt to output assets every time.
>                 test: /mini-css-extract-plugin[\\/]dist[\\/]loader/,
>             },
> ```

yeah , that's great. That solves my problem

**Comment by Superjisan** [comment]
> I was getting the same issue as well, deleting the hard-source cache folder from /node_modules/.cache/hard-source/ has fixed this for me and it has yet to re-appear after more dev on the project. Not sure what caused it in the first place however...
> 
> ![before](https://user-images.githubusercontent.com/1764111/43914892-0b28905a-9c01-11e8-8740-e7f469bf9bb8.png)
> ![after](https://user-images.githubusercontent.com/1764111/43914891-0b122b4e-9c01-11e8-8f69-5786e88d5159.png)

This worked for me, thanks my guy!

**Comment by AndrewBogdanovTSS** [comment]
@Superjisan you didn't fix anything. Just wait for a couple hours and you will get same problem over again. It will require you to delete the cache again and again. What is the purpose of this plugin than if you should always delete the cache and make a full rebuild?

**Comment by charithjayasanka** [comment]
Cleaning node_modules/.cache folder will do it

**Comment by garethweaver** [comment]
As recommended above we've been using [hard-source-webpack-plugin-fixed-hashbug](https://www.npmjs.com/package/hard-source-webpack-plugin-fixed-hashbug) for a few months now and it's working great.

This is PR'd in #497 if you want to follow it.

**Comment by ansballard** [comment]
@kadamwhite from the recent activity it sounds like this PR: https://github.com/mzgoddard/hard-source-webpack-plugin/pull/497 from @conorh is probably a good candidate for checking and merging per your https://github.com/mzgoddard/hard-source-webpack-plugin/issues/525 issue. I don't have much free time these days but I'll see if I can take some time tonight to take a more recent look.

And it's been mentioned a couple times, but this thread is long enough that all the workarounds have been mentioned/disproved several times. If you're stumbling across this thread, be sure to read through before posting possible fixes, as there's already too much noise to be able to quickly understand what's been worked through already. Thanks!

Update: looked through the existing PR and the travis errors are just from the linter failing, mostly on code that's already committed in master, so I made a comment that as far as I can tell it's safe to merge.

**Comment by AndrewBogdanovTSS** [comment]
@garethweaver I've tried **hard-source-webpack-plugin-fixed-hashbug** in my project. At first, it was working as expected, but in couple of hours I've started to get the same error ☹

**Comment by Herz3h** [comment]
Same error, only way I get to "solve it" is by removing cache folder, which makes this pointless if cache is removed all the time. So I removed this plugin from project since it seems unmaintained :/

**Comment by jvantuyl** [comment]
I think this is related to cache corruption.  I didn't have this problem at all, then I experienced an out-of-memory error.  After that, I got these errors until removing the cache folder as instructed above.

**Comment by lovemegowin** [comment]
Add follow code in you `webpack.config.js` can be resolve this issues 
```
// webpack.config.js
...
config.plugins.push(
    new HardSourceWebpackPlugin.ExcludeModulePlugin([
      {
        test: /mini-css-extract-plugin[\\/]dist[\\/]loader/,
      }
    ])
  )
...
```

**Comment by AndrewBogdanovTSS** [comment]
@lovemegowin in what way should it resolve the issue? I had this config right from the start and it doesn't affect cache corruption what so ever

**Comment by freedyc** [comment]
My question:
```
Version: webpack 4.44.2
Time: 4624ms
Built at: 2020-12-11 10:44:07 AM
                                    Asset      Size  Chunks                                      Chunk Names
                                   app.js  4.43 MiB     app  [emitted]                    [big]  app
     fc7b2a59864448e6c572.hot-update.json  48 bytes          [emitted] [immutable] [hmr]
master.fc7b2a59864448e6c572.hot-update.js  4.12 KiB  master  [emitted] [immutable] [hmr]         master
                                master.js  9.71 MiB  master  [emitted]                    [big]  master
 + 3 hidden assets
Entrypoint app [big] = app.css app.js
[./assets/javascripts/zddi/am/dhcp_like/views/main.js] 2.67 KiB {master} [built]
    + 3749 hidden modules
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
[hardsource:19a950bb] Using 326 MB of disk space.
94% after seal[hardsource:19a950bb] Could not freeze ./assets/stylesheets/zddi.scss: Cannot read property 'hash' of undefined
[hardsource:19a950bb] Could not freeze ./node_modules/@dengyongchao/modal/modal.scss: Cannot read property 'hash' of undefined
ℹ ｢wdm｣: Hash: d41d03944d509d378704
Version: webpack 4.44.2
Time: 5698ms
```

The solution is add config
```
{
    new HardSourceWebpackPlugin(),
    new HardSourceWebpackPlugin.ExcludeModulePlugin([
        {
            // HardSource works with mini-css-extract-plugin but due to how
            // mini-css emits assets, assets are not emitted on repeated builds with
            // mini-css and hard-source together. Ignoring the mini-css loader
            // modules, but not the other css loader modules, excludes the modules
            // that mini-css needs rebuilt to output assets every time.
            test: /mini-css-extract-plugin[\\/]dist[\\/]loader/,
        },
    ]),
}
```

**Comment by 0x1af2aec8f957** [comment]
@freedyc 
After my verification, this method is only effective in the first build, but not in the second build.
It is safe to delete the directory `node_modules/.cache` every time you build.

**Comment by VienArchway** [comment]
In nuxtjs app, I set into package.json

```
"scripts": {
    "clear-hard-source-cache": "rm -rf node_modules/.cache/hard-source/"
},
```

`npm run clear-hard-source-cache`

**Comment by AndrewBogdanovTSS** [comment]
@VienArchway how does it help to solve an issue? Such command makes this module pointless since you have to regenerate cache again and again

**Comment by xiaoxixi6633** [comment]
> Same problem here. This issue seems to appear after the latest webpack update (4.16.4 -> 4.16.5)

不是的 我的webpack 版本是4.0.0

**Comment by xiaoxixi6633** [comment]
> I am getting this error with webpack 4.16.4.

I am getting this error with webpack 4.0.0.

**Comment by dazjean** [comment]
https://github.com/mzgoddard/hard-source-webpack-plugin/issues/461#issuecomment-439177290 
When I use this solution to solve the problem, it's an escape behavior to make other loaders work。
```
plugin:[
new HardSourceWebpackPlugin(),
new HardSourceWebpackPlugin.ExcludeModulePlugin({
            // HardSource works with mini-css-extract-plugin but due to how
            // mini-css emits assets, assets are not emitted on repeated builds with
            // mini-css and hard-source together. Ignoring the mini-css loader
            // modules, but not the other css loader modules, excludes the modules
            // that mini-css needs rebuilt to output assets every time.
            test: /mini-css-extract-plugin[\\/]dist[\\/]loader/
        })
]
```

**Comment by xiaoxixi6633** [comment]
> [#461 (comment)](https://github.com/mzgoddard/hard-source-webpack-plugin/issues/461#issuecomment-439177290)
> When I use this solution to solve the problem, it's an escape behavior to make other loaders work。
> 
> ```
> plugin:[
> new HardSourceWebpackPlugin(),
> new HardSourceWebpackPlugin.ExcludeModulePlugin({
>             // HardSource works with mini-css-extract-plugin but due to how
>             // mini-css emits assets, assets are not emitted on repeated builds with
>             // mini-css and hard-source together. Ignoring the mini-css loader
>             // modules, but not the other css loader modules, excludes the modules
>             // that mini-css needs rebuilt to output assets every time.
>             test: /mini-css-extract-plugin[\\/]dist[\\/]loader/
>         })
> ]
> ```

我用的这个 方法 但是还是 有相同的问题，我看大部分人都不再提问了，我也很纳闷

**Comment by dazjean** [comment]
> > [#461 (comment)](https://github.com/mzgoddard/hard-source-webpack-plugin/issues/461#issuecomment-439177290)
> > When I use this solution to solve the problem, it's an escape behavior to make other loaders work。
> > 
> > ```
> > plugin:[
> > new HardSourceWebpackPlugin(),
> > new HardSourceWebpackPlugin.ExcludeModulePlugin({
> >             // HardSource works with mini-css-extract-plugin but due to how
> >             // mini-css emits assets, assets are not emitted on repeated builds with
> >             // mini-css and hard-source together. Ignoring the mini-css loader
> >             // modules, but not the other css loader modules, excludes the modules
> >             // that mini-css needs rebuilt to output assets every time.
> >             test: /mini-css-extract-plugin[\\/]dist[\\/]loader/
> >         })
> > ]
> > ```
> 
> 我用的这个 方法 但是还是 有相同的问题，我看大部分人都不再提问了，我也很纳闷

new HardSourceWebpackPlugin() 必须在之前被使用添加到plugin中。

**Comment by huoyuxin** [comment]
here is a possible solution. please check~  @pustovalov @mzgoddard 
https://github.com/mzgoddard/hard-source-webpack-plugin/pull/519

**Comment by pustovalov** [comment]
I stopped using this plugin after I found this behavior: https://github.com/mzgoddard/hard-source-webpack-plugin/issues/416#issuecomment-614847450

**Comment by recover758126** [comment]
I use this solution to fix the problem, but it is not work, I get the same error after few moments
`
plugin:[
new HardSourceWebpackPlugin(),
new HardSourceWebpackPlugin.ExcludeModulePlugin({
            // HardSource works with mini-css-extract-plugin but due to how
            // mini-css emits assets, assets are not emitted on repeated builds with
            // mini-css and hard-source together. Ignoring the mini-css loader
            // modules, but not the other css loader modules, excludes the modules
            // that mini-css needs rebuilt to output assets every time.
            test: /mini-css-extract-plugin[\\/]dist[\\/]loader/
        })
]
`

**Comment by brainz80** [comment]
Decided to switch to `webpack 5`. Webpack 5 has built-in filesystem caching.

use `cache: false` to disable it.

And 

```js
cache: {
	cacheDirectory: path.resolve(__dirname, 'node_modules/.cache/.temp_cache'),
	type: 'filesystem',
}
```

to define a filesystem cache. Cached data will be stored in `cacheDirectory`.

More info here [https://webpack.js.org/configuration/cache/#cache](https://webpack.js.org/configuration/cache/#cache)
and here #546

**Comment by laniltee** [comment]
I had the same issue with NextJS `"next": "11.1.2"`, `"react": "17.0.2"` and `"react-dom": "17.0.2"`. Removing `node_modules` directory, Removing `package-lock.json` and re-running `npm run build` after `npm install` worked.

**Comment by RyanClementsHax** [comment]
> I had the same issue with NextJS `"next": "11.1.2"`, `"react": "17.0.2"` and `"react-dom": "17.0.2"`. Removing `node_modules` directory, Removing `package-lock.json` and re-running `npm run build` after `npm install` worked.

I had the same exact issue with the same exact versions and the solution was exactly the same (I use yarn instead of npm, but it worked just fine)

**Comment by AndrewBogdanovTSS** [comment]
> > I had the same issue with NextJS `"next": "11.1.2"`, `"react": "17.0.2"` and `"react-dom": "17.0.2"`. Removing `node_modules` directory, Removing `package-lock.json` and re-running `npm run build` after `npm install` worked.
> 
> I had the same exact issue with the same exact versions and the solution was exactly the same (I use yarn instead of npm, but it worked just fine)

it's not a solution at all, you just removed cache folder together with nuking node_modules so of course you don't see an error anymore since new cache is created but that makes this module useless with such "solutions"

**Comment by wesleybl** [comment]
I didn't have this problem but unexpectedly it started to occur:

```
[hardsource:15122d4d] Could not freeze ./app/img/resize-hor.png: Cannot read property 'fileDependencies' of undefined
```

I then realized that I had a node_modules folder on my home. So I deleted it and the error was gone.
